workspace:
  base: /go
  path: src/github.com/UKHomeOffice/kube-cfn-signal

pipeline:
  build_binary:
    image: golang:1.8.1
    commands:
      - go test -v -cover
      - mkdir -p bin
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/kube-cfn-signal_linux_amd64
      - GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o bin/kube-cfn-signal_linux_386
      - GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -o bin/kube-cfn-signal_linux_arm
      - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o bin/kube-cfn-signal_darwin_amd64
      - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o bin/kube-cfn-signal_windows_amd64.exe

  build_docker_image:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t image .

  latest_image_to_quay:
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+kube_cfn_signal" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/kube-cfn-signal:latest
      - docker push quay.io/ukhomeofficedigital/kube-cfn-signal:latest
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+kube_cfn_signal" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/kube-cfn-signal:${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/kube-cfn-signal:${DRONE_TAG}
    when:
      event: tag

  github_release:
    image: plugins/github-release
    files:
      - bin/kube-cfn-signal_linux_amd64
      - bin/kube-cfn-signal_linux_386
      - bin/kube-cfn-signal_linux_arm
      - bin/kube-cfn-signal_darwin_amd64
      - bin/kube-cfn-signal_windows_amd64.exe
    when:
      event: tag

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
